#!/bin/sh
set -eu
"$HOME/.local/bin/cliproxy-tunnel"
open 'https://timmy-mac-mini.tail6d5626.ts.net:8443/management.html#/quota'
printf '%s\n' 'Console opened with Tailscale sign-in. OAuth callback tunnel is ready.'
